# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NMTAnalysis
                                 A QGIS plugin
 Wtyczka QGIS umożliwiająca zautomatyzowane analizy numerycznych modeli terenu.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-12
        copyright            : (C) 2020 by Eryk Chełchowski
        email                : erwinek1998@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NMTAnalysis class from file NMTAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .MainMenu import NMTAnalysis
    return NMTAnalysis(iface)
