# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NMTMainMenu
                                 A QGIS plugin
 Wtyczka QGIS umożliwiająca zautomatyzowane analizy numerycznych modeli terenu.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Eryk Chełchowski
        email                : erwinek1998@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtWidgets
from qgis.PyQt import uic

from ..RasterCutter.RasterCutter import RasterCutter
from ..GeneratePoints.GeneratePoints import GeneratePoints
from ..utils import InfoBox

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'MainMenu_UI.ui'))


class NMTMainMenu(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(NMTMainMenu, self).__init__(parent)
        self.setupUi(self)
        self.parent = parent
        self.plugin_dir = os.path.dirname(__file__)

        # Analiza punktow wys
        self.generatePoints = GeneratePoints(self)
        self.btn_gen_points.clicked.connect(self.generatePoints.run)

        # Potnij raster
        self.rasterCutter = RasterCutter(self)
        self.btn_split_raster.clicked.connect(self.rasterCutter.run)

        # O wtyczce
        self.btn_about.clicked.connect(self.show_info_about_plugin)

    def show_info_about_plugin(self):
        InfoBox(
            self,
            'Wtyczka powstała na potrzeby pracy licencjackiej.\n'
            'Temat: "Opracowanie wtyczki QGIS umożliwiającej\n'
            'zautomatyzowane analizy numerycznych modeli terenu"\n'
            'Autor: Eryk Chełchowski\n',
            title='O wtyczce - Analiza NMT'
        ).button_ok()
