# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NMTMainMenu
                                 A QGIS plugin
 Wtyczka QGIS umożliwiająca zautomatyzowane analizy numerycznych modeli terenu.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Eryk Chełchowski
        email                : erwinek1998@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys

from qgis.PyQt import QtWidgets, QtGui
from qgis.PyQt import uic
from qgis.PyQt.QtWidgets import QMessageBox

from ..Generate3DModel.Generate3DModel import Generate3DModel
from ..GenerateAspect.GenerateAspect import GenerateAspect
from ..GenerateHillshade.GenerateHillshade import GenerateHillshade
from ..GeneratePoints.GeneratePoints import GeneratePoints
from ..GenerateSlope.GenerateSlope import GenerateSlope
from ..GenerateStatistics.GenerateStatistics import GenerateStatistics
from ..RasterCutter.RasterCutter import RasterCutter
from ..SetProjection.SetProjection import SetProjection
from ..utils import normalize_path

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'MainMenu_UI.ui'))


class NMTMainMenu(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None, plugin_path=''):
        super(NMTMainMenu, self).__init__(parent)
        self.setupUi(self)
        self.parent = parent
        self.plugin_path = plugin_path
        self.icon_path = normalize_path(
            os.path.join(self.plugin_path, 'images//icon.png'))
        self.icon = QtGui.QIcon(self.icon_path)
        self.plugin_dir = os.path.dirname(__file__)
        self.qgis2threejs_exists = True
        self.q23js = None

        # Analiza punktow wysokoscowych
        self.generatePoints = GeneratePoints(self)
        self.btn_gen_points.clicked.connect(self.generatePoints.run)

        # Generowanie statystyki
        self.generateStatistics = GenerateStatistics(self)
        self.btn_gen_stat.clicked.connect(self.generateStatistics.run)

        # Wygeneruj model nachylenia
        self.generateSlope = GenerateSlope(self)
        self.btn_gen_slope.clicked.connect(self.generateSlope.run)

        # Wygeneruj model cieniowania
        self.generateHillshade = GenerateHillshade(self)
        self.btn_gen_hillshade.clicked.connect(self.generateHillshade.run)

        # Wygeneruj model ekspozycji
        self.generateAspect = GenerateAspect(self)
        self.btn_gen_aspect.clicked.connect(self.generateAspect.run)

        # Wygeneruj model 3D
        self.qgis2threejs_path = normalize_path(
            os.path.join(self.plugin_path, '..//Qgis2threejs'))
        if os.path.exists(self.qgis2threejs_path) and self.qgis2threejs_exists:
            sys.path.insert(1, self.qgis2threejs_path)
            import Qgis2threejs
            self.q23js = Qgis2threejs
        self.generate3DModel = Generate3DModel(self)
        self.btn_gen_model3d.clicked.connect(self.generate3DModel.run)

        # Potnij raster
        self.rasterCutter = RasterCutter(self)
        self.btn_split_raster.clicked.connect(self.rasterCutter.run)

        # Nadaj/przypisz odwzorowanie
        self.setProjection = SetProjection(self)
        self.btn_set_projection.clicked.connect(self.setProjection.run)

        # O wtyczce
        self.btn_about.clicked.connect(self.show_info_about_plugin)

    def show_info_about_plugin(self):
        QMessageBox.information(
            self, 'O wtyczce - Analiza NMT',
            'Wtyczka powstała na potrzeby pracy licencjackiej.\n'
            'Temat: "Opracowanie wtyczki QGIS umożliwiającej\n'
            'zautomatyzowane analizy numerycznych modeli terenu"\n'
            'Autor: Eryk Chełchowski\n',
            QMessageBox.Ok)
