from qgis.PyQt.QtCore import QVariant
from qgis.core import QgsField

update_fields_list = [QgsField("id", QVariant.String, 'string'),
                      QgsField("description_href", QVariant.String, 'string'),
                      QgsField("description_title", QVariant.String, 'string'),
                      QgsField("description_nilreason", QVariant.String,
                               'string'),
                      QgsField("description", QVariant.String, 'string'),
                      QgsField("descriptionreference_href", QVariant.String,
                               'string'),
                      QgsField("descriptionreference_title", QVariant.String,
                               'string'),
                      QgsField("descriptionreference_nilreason",
                               QVariant.Double,
                               'double'),
                      QgsField("identifier_codespace", QVariant.String,
                               'string'),
                      QgsField("identifier", QVariant.String, 'string'),
                      QgsField("location_location_pkid", QVariant.String,
                               'string'),
                      QgsField("mianownikskali", QVariant.Int, 'integer'),
                      QgsField("kodkarto", QVariant.String, 'string'),
                      QgsField("uwagi", QVariant.String, 'string'),
                      QgsField("parametr", QVariant.Double, 'double', 20, 1),
                      QgsField("warstwa", QVariant.String, 'string'),
                      QgsField("obiektprzedstawiany1_owns", QVariant.Bool,
                               'boolean'),
                      QgsField(
                          "obiektprzedstawiany1_bt_referencjadoobiektu_pkid",
                          QVariant.String, 'string'),
                      QgsField("mz_ogolnyobiekt_href", QVariant.String,
                               'string'),
                      QgsField("mz_ogolnyobiekt_title", QVariant.String,
                               'string'),
                      QgsField("mz_ogolnyobiekt_nilreason", QVariant.String,
                               'string'),
                      QgsField("mz_ogolnyobiekt_owns", QVariant.Bool,
                               'boolean'),
                      QgsField("mz_ogolnyobiekt_mz_ogolnyobiekt_id",
                               QVariant.String,
                               'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_description_href",
                          QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_description_title",
                          QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_description_nilreason",
                          QVariant.String, 'string'),
                      QgsField("mz_ogolnyobiekt_mz_ogolnyobiekt_description",
                               QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_descriptionreference_href",
                          QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_descriptionreference_title",
                          QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_descriptireference_nilreason",
                          QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_identifier_codespace",
                          QVariant.String, 'string'),
                      QgsField("mz_ogolnyobiekt_mz_ogolnyobiekt_identifier",
                               QVariant.String, 'string'),
                      QgsField(
                          "mz_ogolnyobiekt_mz_ogolnyobiekt_location_location_pkid",
                          QVariant.String, 'string')]
